### ISSUE TITLE
Tool cannot handle extremely large combinations

### ISSUE THREAD

**Issue by joeasds** [ByronPhung/combinational-logic-simulator#1]
Is there a limit to the number of this input and id, and how can they be expanded?

**Comment by ByronPhung** [comment]
Since I defined inputs "I" to use positive numbers instead of something more limiting like A-Z, then the limit is based on the number of inputs you define in the .in circuit files (assuming you define them correctly). If you care to create a large enough file, then the limit should theoretically be the largest positive number that Python can handle on the machine running the script :P.

**Comment by joeasds** [comment]
What is the largest positive number that Python can handle on the machine running the script, I use 159 ID and 36 input,but it fails.

**Comment by ByronPhung** [comment]
Well, unless you're working with over 2 billion, I don't think you need to worry about that.

As for your input, you can only select from the ID numbers up to the number of gates you have. This output is generated for you once you specify a valid circuit file in the first part of the script.

For example, if you use the fulladder-samp[le1.in file, you will get the following generated table and can only specify 0 through 5 (the ID column on the left).

ID    Name    Type    Inputs
-------------------------------
0     XOR1     XOR    I0   I1
1     SUM      XOR     0   I2
2     AND2    AND    I0  I2
3     AND1    AND    I0  I1
4     AND3    AND    I1  I2
5     CARRY   OR      2    3   4

**Comment by joeasds** [comment]
I used pythcharm to run the program, found that the memory peaked, occured the final memory error, is my file .in is a problem or the computer's memory is not enough?  Can the memory can be released at run time?

**Comment by ByronPhung** [comment]
Can you attach or paste your .in file here? I suspect it's that, but I'll have to see it firsthand to confirm.

**Comment by joeasds** [comment]
Please help confirm it.

**Comment by joeasds** [comment]
Please help confirm it.
[test11.zip](https://github.com/ByronPhung/combinational-logic-simulator/files/1862359/test11.zip)

**Comment by ByronPhung** [comment]
@joeasds Thanks for the circuit file. You did have 1 typo on line "18 ... NAND2_0 ... nan ... 0 i1" - just need to fix nan to nand. However, I did confirm that the script did reach its limit in terms of memory. To be more precise, it had to calculate 2^36 combinations, which is 68,719,476,736 and well past what most computers can handle (these are combinations of [0, 1], e.g. [0, 0, ... 36th 0] to [1, 1, ... 36th 1]).

On the other hands, thanks to this investigation and your report, I did find a flaw in the script that limited it in cases like yours. Therefore, I re-opened this case and will apply a fix that I successfully tested with your circuit. I'll comment on this case and let you know when the patch is applied for you to try again.

**Comment by joeasds** [comment]
I tried to use up to 25 inputs (0-24) to run sucessfully, expecting your changes to run a greater combination!Thanks a lot.

**Comment by ByronPhung** [comment]
@joeasds I just pushed v1.1.0, which should address the memory issue and implemented a number of other changes as well. Please refer to the README for updated running instructions.

Please do note that your 36-input circuit means that there will be 2^n, or 68,719,476,736, combinations as mentioned earlier, so this may take a few hours depending on how fast your computer is. Also, because of this, I highly recommend using the new output file option (-o, --out <output-file-path>) so that the truth table can be saved in that file instead of printing to the console, which would also shave off some time too.

I'll keep this issue open and wait for your confirmation, so please do let me know once everything works better for you!

**Comment by joeasds** [comment]
I found that the modified files can output results in the console successfully, and are running. But I can't find the command to put the output in a special file. I tried it several times like (e.g. python main.py [-o path/to/out_file] path\to\circuit_file.in) at the beginning, but I got an error. Can you give a demonstration of the specific command or a example？

**Comment by ByronPhung** [comment]
Here's a working example that I had with your circuit file:

```python main.py -o output.txt D:\Downloads\test11\test11.in```

This stores the output in an "output.txt" file in the current directory. The order also doesn't matter either - you can even say ```python main.py path/to/circuit_file -o path/to/output```.

Let me know if this works for you. Otherwise, please paste the real command you're using here and I'll try to analyze that.

**Comment by joeasds** [comment]
Thank you for two examples, I try them successfully. And it is running..

**Comment by ByronPhung** [comment]
Awesome! I'm glad I could help you out!

**Comment by joeasds** [comment]
There are new questions of the tools. Can the form of the change be made? I ran for two days and had more than 600 Mb, but I haven't finished yet. . It may take some months even year. Another, Can I join the buffer gate in the basic gate? I look forward to your suggestions, thank you！

**Comment by joeasds** [comment]
There are new questions of the tool. Can the form of the change be made? I ran for two days and had more than 600 Mb, but I haven't finished yet. . It may take some months even year. Another, Can I join the buffer gate in the basic gate? I look forward to your suggestions, thank you！

**Comment by joeasds** [comment]
There are new questions of the tools. Can the form of the result be changed? I ran for two days and had more than 600 Mb, but I haven't finished yet. . It may take some months even year. Another, Can I join the buffer gate in the basic gate? I look forward to your suggestions, thank you！

**Comment by ByronPhung** [comment]
What kind of format are you looking for? Unfortunately, yeah, the long time is just because it's calculating for every single combination (over 68 billion) and there is no sort of optimized algorithm for processing every single combination.

As for the buffer gate, yeah, I should be able to easily add that.

**Comment by joeasds** [comment]
If I determine the value of the output q (e.g. ID4 = 1), in  the output whose value is not q to remove. And assuming it can only be written by the output value and remove the input value,because the order of input is very consistent.

**Comment by ByronPhung** [comment]
I'm sorry, I'm having trouble understanding your request. Are you asking if we can remove certain input or output columns?

**Comment by joeasds** [comment]
What I mean is basically the same as what you said, there is a example.
the original result
I0 I1 I2 XOR1 SUM AND3
0  0  0  0    0   0
0  0  1  0    1   0
0  1  0  1    1   0
0  1  1  1    0   1
1  0  0  1    1   0
1  0  1  1    0   0
1  1  0  0    0   0
1  1  1  0    1   1
```
We can turn it into a new form:
XOR1 SUM AND3
0    0   0
0    1   0
1    1   0
1    0   1
1    1   0
1    0   0
0    0   0
0    1   1
```

if we want to get a certain output(0 0 0):
I0 I1 I2 XOR1 SUM AND3
0  0  0  0    0   0
1  1  0  0    0   0
```

**Comment by ByronPhung** [comment]
Thanks for the clarification. It certainly is possible to do something like that, but the biggest issue would be to accomplish these tasks in a reasonable/practical time for large circuits like your 36-input, 159-gate circuit. Both of the requested features require post-processing of some sort _after_ the table is already generated (although the columns could be altered on first execution BUT it's irreversible unless you re-run).

The best alternative I can think of right now is to implement a CSV-format output mode so that you can use Microsoft Excel (or your own CSV parser) and filter out the data however you want. Being able to use Excel or your own CSV parser would allow you to filter out the data that is already generated in any way (limited to capabilities of Excel or your CSV parser) without having to wait for me to implement some sort of support in my tool.

Would that approach work for you? I imagine this being a flag like --csv-format so that your output file will store CSV-friendly lines (as opposed to space-separated columns/rows) and then you can open that output file with Excel or a similar program.

**Comment by joeasds** [comment]
I'm interested in the CSV, and how can I get the form, will it run fast?

**Comment by joeasds** [comment]
Thank you! I'm interested in the CSV, and how can I get the form, will it run fast?

**Comment by ByronPhung** [comment]
If you have an existing output file with a table, then you should be able to just do a Replace All with your text editor to change all whitespace into commas and then you can just change the file extension to .csv.

For example:
```
I0 I1 I2 XOR AND
0  0  0  1      1
0  0  1  0      0
...
```
would change to
```
I0,I1,I2,XOR,AND
0,0,0,1,1
0,0,1,0,0
```

As for newer tables, I should be able to just implement a --format-csv flag that you can use so that your output file is automatically in CSV format.

Runtime should not change from as it is now, which means that circuits with large amounts of combinations like yours would still take extremely long. The only solution I can think of is implementing some sort of multi-threaded programming, but the main issue is that something too big / number of threads (for example, 4 on most people's PCs) is still too big. As a result, I don't believe I'll be able to tackle the performance issue on large circuits unless I explore something like distributed computing or similar, but that would expand this tool to be much greater than it is as a simple Python script.

If you don't care about having a full truth table and just want to see specific input, then the most I could probably do is allow you to input your own combination, e.g., 00001111 or 0x0F, and have the tool generate just the output for that combination alone.

**Comment by joeasds** [comment]
Thanks for your suggestion, I will try other ways to run the large circuits. Can you add a buffer into the basic gate?

**Comment by ByronPhung** [comment]
Sorry for that. I can definitely add the buffer gate, though. I'll keep you posted.

Thanks for using and testing out my tool!

**Comment by joeasds** [comment]
Thanks a lot! May I use the distributed computing or similar to expand the tool, is it difficult?

**Comment by ByronPhung** [comment]
Unfortunately, distributed computing (or similar) is out of my skill set, so I can't answer on how difficult it is, but I know for sure it's not a simple topic as it involves setting up a system of independent machines that can communicate with each other to process something simultaneously.

Parallel/multi-threaded programming are similar areas that involve the same machine, but I have yet to successfully figure this out for this tool (I have attempted a few times already).

**Comment by joeasds** [comment]
Thanks for your answer!! If the loop body is written in C, is it possible that the speed will be faster?

**Comment by ByronPhung** [comment]
No problem!

As for your question about writing the loop in C (or any other different language for that matter), I don't believe that would solve the performance issue.

Unfortunately, this is just the nature of working with large data sets (like 68 billion combinations in your case). Writing the same loop in a different language doesn't change the fact that the machine has to make 68 billion calculations - you have to find a way to break up those 68 billion calculations and calculate them simultaneously.

The simplest example I can think of to demonstrate this is, for example, having 68 billion computers perform 1 calculation each at the same time. If they each take 1 second per calculation, then you can do 68 billion calculations in 1 second. On the other side of the spectrum, if you have only 1 computer (like in our case), then you would need 68 billion seconds to do the same calculations. 

This is why I think some sort of distributed system or multi-threaded programming approach will be the solution to this issue, although I would definitely lean towards a more distributed system because most user PCs have at most 4-8 cores. If we continue with the example above, using 4 cores would mean you still need 17 billion seconds to do 68 billion calculations. Lastly, on the topic of distributed computing, unfortunately, I don't have the resources (nor a compelling reason or ROI to invest money in those resources) for this tool alone.

P.S. v1.2.0 was released last night that introduces the buffer gate as well as the --format-csv option.

**Comment by joeasds** [comment]
Thanks for your suggestion!! I think the multi-threaded programming approach may be difficuit. I will try the new format, what do you think about guessing from the output node to input this scheme?  Do you think using the cython to improve the speed, though it is not very helpful for the large circuit.

**Comment by joeasds** [comment]
Thanks for your suggestion!! I think the multi-threaded programming approach may be difficuit. I will try the new format, what do you think about guessing from the output node to input this scheme? Do you think using the cython to improve the speed, but it is not helpful for the large circuit.

**Comment by joeasds** [comment]
There is nothing wrong with what you said. I tried to change the form of the output, including displaying the output only. It does not solve the big data problem. Although it can make it 10 times faster, It is really difficult to do for large circuit combinations. Can you enter part of the value and calculate their simulation results? I appreciate you.

**Comment by ByronPhung** [comment]
If I understood that correctly, you are asking if you can input your desired combination manually? For example, you would like to be able to input something like 000011111 and get the result for just 000011111?

**Comment by joeasds** [comment]
Right, what's more, if I  want to t input the "xx0011xx" and get the result for xx0011xx, is that OK?
P.S. xx0011xx has 16 combinations

**Comment by ByronPhung** [comment]
@joeasds Thanks for that example and suggestion. The single direct input should be simple to implement, but I'll have to experiment and get back to you on the wildcard support. The main reason for this is that I'll have to see if I can implement in the same way that fixed the original large combination memory issue.

**Comment by joeasds** [comment]
Thanks! I'm looking forward for you!
